# Site settings
title: Homepage
baseurl: ""
url: "https://optray.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Rui Zhang
  desc: Beijing, China
  email: rayzhang@amss.ac.cn
  selfie: assets/img/rui.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  google_plus:
  instagram:
  keybase:
  linkedin: 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
