# Site settings
title: Rui's Homepage
description: Rui Zhang
baseurl: ""
url: "https://optray.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Rui Zhang
  role: Assistant Professor
  affiliation: Gaoling School of Artificial Intelligence
  institution: Renmin University of China
  location: Beijing, China
  email: rayzhang@ruc.edu.cn
  selfie: assets/img/rui-portrait.jpg
  scholar: https://scholar.google.com/citations?user=8V50qncAAAAJ&hl=en
  github: https://github.com/optray

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  google_plus:
  instagram:
  keybase:
  github: optray
  linkedin:
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
